POST https://sheva.com.ar/admin/extapi/validate_user
Content-Type: application/json
Accept: application/json
File-Token: GW&H$H&W)F^Q0q#F^#$)G#)G^a^)#ASF^)#)^G#G&g$L%YUL$WTRAW@D#%A)%^f)#$G^S%#L

{
   "uname":"kiosko1@email.com",
   "pwd" : "DEMO"
}
